// This file is generated by `cargo run -p task_models --bin export_ipc_types`.
// Do not edit it by hand.

export type ConversationState = "idle" | "listening" | "holding_for_more" | "clarifying" | "intent_locked" | "speaking" | "interrupted";

export type ExecutionState = "not_started" | "drafting_plan" | "waiting_confirmation" | "executing" | "paused" | "completed" | "failed";

export type TaskState = "idle" | "listening" | "understanding" | "planning" | "waiting_approval" | "executing" | "paused" | "completed" | "cancelled" | "reverted" | "failed";

export type StepState = "pending" | "running" | "waiting_approval" | "completed" | "failed" | "skipped" | "blocked" | "reverted";

export type ApprovalFlow = "not_needed" | "requested" | "editing" | "granted" | "authorizing" | "denied" | "done";

export type RiskLevel = "low" | "medium" | "high";

export type PlanState = "drafting" | "ready" | "approved" | "cancelled";

export type IntentQuestion = { id: string, text: string, };

export type Intent = { goal?: string, scope?: string, constraints?: string, exclusions?: string, unresolvedQuestions: Array<IntentQuestion>, };

export type PlanStep = { id: string, description: string, };

export type Plan = { title?: string, steps: Array<PlanStep>, planState: PlanState, };

export type CompletionChanges = { created: number, modified: number, moved: number, deleted: number, network?: boolean, };

export type CompletionSummary = { title?: string, outcome: string, changes: CompletionChanges, rollbackAvailable?: boolean, rollbackTimeRemaining?: string, };

export type ApprovalRequest = { action: string, willAffect: Array<string>, willNotAffect: Array<string>, impactSummary?: string, command?: string, };

export type TimelineStep = { id: string, description: string, impact?: string, status: StepState, };

export type TranscriptChunkInput = { text: string, isFinal: boolean, };

export type ConversationSlice = { state: ConversationState, transcript: string, };

export type ExecutionProgress = { current: number, total: number, };

export type ExecutionSlice = { state: ExecutionState, progress?: ExecutionProgress, };

export type ApprovalSnapshot = { state: ApprovalFlow, request?: ApprovalRequest, };

export type TaskSnapshot = { id?: string, title?: string, summary?: string, risk?: RiskLevel, scope?: string, state: TaskState, intent: Intent, plan: Plan, completion?: CompletionSummary, };

export type SystemState = { conversation: ConversationSlice, execution: ExecutionSlice, currentTask: TaskSnapshot, approval: ApprovalSnapshot, timeline: Array<TimelineStep>, };

